name: 'servicenow_integration_tests'
version: '0.1.0'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  servicenow:
    servicenow_task_identifier: "task_data"
    servicenow_task_sla_identifier: "task_sla_data"
    servicenow_sys_user_identifier: "sys_user_data"
    servicenow_problem_identifier: "problem_data"
    servicenow_problem_task_identifier: "problem_task_data"
    servicenow_incident_identifier: "incident_data"
    servicenow_change_task_identifier: "change_task_data"
    servicenow_change_request_identifier: "change_request_data"
